module.exports = function(grunt) {
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        banner:'/*!\n * Copyright (c) Christopher Keefer, <%= grunt.template.today("yyyy") %>.\n' +
            ' * <%= pkg.name %>: V<%= pkg.version %>.\n' +
            ' * This file is generated by grunt - do not edit directly.\n' +
            ' * Alter source files as needed, then run `grunt` in project directory.\n' +
            ' * Compiled: <%= grunt.template.today("yyyy-mm-dd") %> \n */\n\n',
        uglify:{
            options:{
                banner:'<%= banner %>',
                report:'min'
            },
            behold:{
                options:{
                    sourceMappingURL:'Behold.min.map',
                    sourceMapPrefix:2,
                    sourceMap:'dist/Behold.min.map'
                },
                src:'src/Behold.js',
                dest:'dist/Behold.min.js'
            }
        },
        doxx: {
            all: {
                src:'src',
                ignore:'node_modules,docs',
                target:'docs'
            }
        }
    });

    // Load plugins for each task
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-doxx');

    // Tasks
    grunt.registerTask('default', ['uglify', 'doxx']);
    grunt.registerTask('justCode', ['uglify']);
    grunt.registerTask('justDocs', ['doxx']);
};
