module.exports = function(grunt) {
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        banner:'/*!\n * Copyright (c) Christopher Keefer, 2014.\n' +
            ' * <%= pkg.name %>: V<%= pkg.version %>.\n' +
            ' * This file is generated by grunt - do not edit directly.\n' +
            ' * Alter source files as needed, then run `grunt` in project directory.\n' +
            ' * Compiled: <%= grunt.template.today("yyyy-mm-dd") %> \n */\n\n',
        uglify:{
            options:{
                banner:'<%= banner %>',
                report:'min'
            },
            behold:{
                options:{
                    sourceMappingURL:'Behold.min.map',
                    sourceMapPrefix:2,
                    sourceMap:'Behold.min.map'
                },
                src:'Behold.js',
                dest:'Behold.min.js'
            }
        },
        yuidoc: {
            compile: {
                name: '<%= pkg.name %>',
                description: '<%= pkg.description %>',
                version: '<%= pkg.version %>',
                url: '<%= pkg.homepage %>',
                options: {
                    paths: './',
                    outdir: './docs/'
                }
            }
        }
    });

    // Load plugins for each task
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-contrib-yuidoc');

    // Tasks
    grunt.registerTask('default', ['uglify', 'yuidoc']);
    grunt.registerTask('justCode', ['uglify']);
    grunt.registerTask('justDocs', ['yuidoc']);
};
