module.exports = function(grunt) {
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        banner:'/*!\n * Copyright (c) Christopher Keefer, <%= grunt.template.today("yyyy") %>.\n' +
            ' * <%= pkg.name %>: V<%= pkg.version %>.\n' +
            ' * This file is generated by grunt - do not edit directly.\n' +
            ' * Alter source files as needed, then run `grunt` in project directory.\n' +
            ' * Compiled: <%= grunt.template.today("yyyy-mm-dd") %> \n */\n\n',
        concat:{
            options:{
                stripBanners:{
                    block:true,
                    line:true
                },
                process:false,
                separator:';\n' // Ensures an ending semi-colon after each file we concatenate
            },
            behold:{
                src:[
                    'src/Behold.js'
                ],
                dest:'dist/Behold-<%= pkg.version %>.js'
            }
        },
        uglify:{
            options:{
                banner:'<%= banner %>',
                report:'min'
            },
            behold:{
                options:{
                    sourceMappingURL:'Behold.min.map',
                    sourceMapPrefix:2,
                    sourceMap:'dist/Behold.min.map'
                },
                src:'dist/Behold-<%= pkg.version %>.js',
                dest:'dist/Behold-<%= pkg.version %>.min.js'
            }
        },
        doxx: {
            all: {
                src:'src',
                ignore:'node_modules,docs',
                target:'docs'
            }
        }
    });

    // Load plugins for each task
    grunt.loadNpmTasks('grunt-contrib-concat');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-doxx');

    // Tasks
    grunt.registerTask('default', ['concat', 'uglify', 'doxx']);
    grunt.registerTask('justCode', ['concat', 'uglify']);
    grunt.registerTask('justDocs', ['doxx']);
};
